// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

#include <QCryptographicHash>
#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QProcess>
#include <QProcessEnvironment>
#include <QSaveFile>
#include <QStandardPaths>
#include <cstdio>

namespace KWinPermission {
inline QString executable() {
    // Match KWin's /proc/<pid>/exe identity, including /home -> /var/home.
    return QFileInfo(QStringLiteral("/proc/self/exe")).canonicalFilePath();
}

inline QString fileName(const QString& path) {
    return "io.github.keithxc.DeskPort.kwin-display-" +
        QString::fromLatin1(QCryptographicHash::hash(path.toUtf8(), QCryptographicHash::Sha256).toHex()) + ".desktop";
}

inline QByteArray entry(const QString& path) {
    // KWin uses QProcess::splitCommand, rather than a shell, for Exec matching.
    // Escape the desktop-entry string layer as well as the command quoting.
    QString command = path;
    command.replace('"', QStringLiteral("\"\"\""));
    command = '"' + command + '"';
    command.replace('\\', QStringLiteral("\\\\"));
    command.replace('\n', QStringLiteral("\\n"));
    command.replace('\r', QStringLiteral("\\r"));
    return ("[Desktop Entry]\nType=Application\nName=DeskPort display permission\n"
            "NoDisplay=true\nExec=" + command +
            "\nX-KDE-Wayland-Interfaces=zkde_screencast_unstable_v1\n"
            "X-DeskPort-Executable=" + QString::fromLatin1(path.toUtf8().toBase64()) + "\n").toUtf8();
}

inline bool install(QString& error) {
    const QString path = executable();
    const QString directory = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation) + "/applications";
    if (path.isEmpty() || !QDir().mkpath(directory)) {
        error = "deskport-display cannot create its KWin permission entry in " + directory;
        return false;
    }
    const QString target = directory + '/' + fileName(path);
    const QByteArray content = entry(path);
    QFile existing(target);
    const bool unchanged = existing.open(QIODevice::ReadOnly) && existing.readAll() == content;
    existing.close();
    if (!unchanged) {
        QSaveFile file(target);
        if (!file.open(QIODevice::WriteOnly) || file.write(content) != content.size() || !file.commit()) {
            error = "deskport-display cannot save its KWin permission entry: " + target;
            return false;
        }
    }
    // Only remove byte-for-byte entries generated by us for vanished mounts.
    // Keep entries for other running AppImages and all user/package entries.
    for (const auto& name : QDir(directory).entryList({"io.github.keithxc.DeskPort.kwin-display-*.desktop"}, QDir::Files)) {
        QFile old(directory + '/' + name);
        if (!old.open(QIODevice::ReadOnly)) continue;
        const auto bytes = old.readAll();
        old.close();
        QString oldPath;
        for (const auto& line : bytes.split('\n'))
            if (line.startsWith("X-DeskPort-Executable=")) oldPath = QString::fromUtf8(QByteArray::fromBase64(line.mid(21)));
        if (!oldPath.isEmpty() && name == fileName(oldPath) && bytes == entry(oldPath) && !QFileInfo::exists(oldPath)) old.remove();
    }
    // AppImage's Qt/library environment must not leak into the system KDE tool.
    auto env = QProcessEnvironment::systemEnvironment();
    for (const auto& key : {"APPIMAGE", "APPDIR", "LD_LIBRARY_PATH", "LD_PRELOAD", "QT_PLUGIN_PATH", "QT_QPA_PLATFORM_PLUGIN_PATH", "QML_IMPORT_PATH", "QML2_IMPORT_PATH"}) env.remove(key);
    QProcess refresh;
    refresh.setProcessEnvironment(env);
    refresh.start("kbuildsycoca6", {"--noincremental"});
    if (!refresh.waitForFinished(4000)) {
        refresh.kill();
        refresh.waitForFinished(1000);
        // KDE also watches applications/. The caller retries new connections
        // for a bounded interval, including when the tool is unavailable.
        fprintf(stderr, "deskport-display: KDE permission cache refresh unavailable; waiting for desktop discovery\n");
    } else if (refresh.exitStatus() != QProcess::NormalExit || refresh.exitCode() != 0) {
        fprintf(stderr, "deskport-display: KDE permission cache refresh failed; waiting for desktop discovery\n");
    }
    return true;
}
}
